---
deployment:
  tasks:
    - export DEPLOYPATH=/home/user/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp assets $DEPLOYPATH
    - /bin/cp projects $DEPLOYPATH
    - /bin/cp js $DEPLOYPATH
    - /bin/cp Brandon_Aguilar_Resume_v2.pdf $DEPLOYPATH
    - /bin/cp robots.txt $DEPLOYPATH