---
deployment:
  tasks:
    - export DEPLOYPATH=/home/branwqic/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R projects $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp Brandon_Aguilar_Resume_v2.pdf $DEPLOYPATH
    - /bin/cp robots.txt $DEPLOYPATH